In [1]:
import numpy as np

# ndarray

In [2]:
#1차원
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)


In [5]:
#2차원
array2 = np.array([[1,2,3],
                 [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)


In [6]:
#2차원
array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)

array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)


In [9]:
print('array1 : {}차원, array2 : {}차원, array3 : {}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 : 2차원


In [8]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


# data type
- ndarray내의 데이터 타입은 같은 데이터 타입만 가능하다.
- int, float 함께 있을 수 없음

## type

In [13]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [14]:
list2 = [1,2,'test']
array2 = np.array(list2)

print(array2, array2.dtype)
#string으로 바뀜

['1' '2' 'test'] <U11


In [15]:
list3 = [1,2,3.0]
array3 = np.array(list3)

print(array3, array3.dtype)

[1. 2. 3.] float64


## .astype()

In [16]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')

print(array_float, array_float.dtype)

[1. 2. 3.] float64


# ndarray 생성

## arange

In [17]:
sequence_array = np.arange(10)
print(sequence_array)

print(sequence_array.dtype, sequence_array.shape) #1차원

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


## zeros

In [18]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


## ones

In [19]:
one_array = np.ones((3,2), dtype = 'int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


# ndarray 차원과 크기를 변경
## reshape()

In [21]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array1:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array1:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- reshape(-1,n) : -1을 하면, 적절한 값으로 알아서

In [22]:
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape : ', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape : ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape :  (2, 5)
array3 shape :  (5, 2)


## reshape(-1,1)
- 여러 개의 row를 가지되, 반드시 1개의 칼럼을 가진 ndarray로
- 3차원 -> 2차원
- 1차원 -> 2차원

In [28]:
array1 =  np.arange(8)
array3d = array1.reshape((2,2,2))
print('dimension : ', array3d.ndim)
print('array3d:\n', array3d.tolist())
print('\n')
#3차원 -> 2차원
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('dimension : ', array5.ndim)
print('array5 shape : ', array5.shape)
print('\n')
#1차원 -> 2차원
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('dimension : ', array6.ndim)
print('array6 shape : ', array6.shape)

dimension :  3
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
dimension :  2
array5 shape :  (8, 1)


array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
dimension :  2
array6 shape :  (8, 1)


# indexing

## 특정 데이터 추출

In [31]:
array1 = np.arange(1,10)
array1

val = array1[2]
print('value : ', val)
print(type(val))

value :  3
<class 'numpy.int32'>


In [32]:
print('맨 뒤의 값 : ', array1[-1], '맨 뒤에서 두번째 값 : ', array1[-2])

맨 뒤의 값 :  9 맨 뒤에서 두번째 값 :  8


In [33]:
array1[0] = 9
array1[8] = 9

array1

array([9, 2, 3, 4, 5, 6, 7, 8, 9])

- axis = 0 : row
- axis = 1 : column

## 슬라이싱(slicing)

In [36]:
array1 = np.arange(1,10)
print(array1)

array3 = array1[:3]
print(array3)

[1 2 3 4 5 6 7 8 9]
[1 2 3]


In [38]:
print(array1[:3])
print(array1[3:])
print(array1[:])

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [39]:
array2d = array1.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
#행을 1차원으로 반환
print(array2d[0])
print(array2d[1])

print('array2d[0] shape : ', array2d[0].shape, 'array2d[1] shape : ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape :  (3,) array2d[1] shape :  (3,)


## Fancy Indexing
- 일정한 인덱싱 집함을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환

In [44]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
array2d[[0,1],2]

array([3, 6])

In [46]:
array2d[[0,1],0:2]

array([[1, 2],
       [4, 5]])

In [47]:
array2d[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

## Boolean Indexing
- 특정 조건에 해당하는True/False 인덱싱 집합을 기반으로 True값만 반환

In [50]:
array1d = np.arange(10)
print(array1d > 5)
print(array1d[array1d>5])

[False False False False False False  True  True  True  True]
[6 7 8 9]


# 정렬

## np.sort() & .sort()

- 원본은 그대로

In [53]:
array1 = np.array([3,1,9,5])
print('original : ', array1)

sort_array = np.sort(array1)
print('np.sort() 후 반환된  : ', sort_array)
print('np.sort() 후 original  : ', array1)

original :  [3 1 9 5]
np.sort() 후 반환된  :  [1 3 5 9]
np.sort() 후 original  :  [3 1 9 5]


In [59]:
print('오름차순',np.sort(array1))
print('내림차순',np.sort(array1)[::-1])
print('original array : ', array1)

오름차순 [1 3 5 9]
내림차순 [9 5 3 1]
original array :  [1 3 5 9]


- return 값 x
- 원본 행렬자체를 정렬

In [54]:
array1 = np.array([3,1,9,5])
print('original : ', array1)

sort_array = array1.sort()
print('np.sort() 후 반환된  : ', sort_array)
print('np.sort() 후 original  : ', array1)

original :  [3 1 9 5]
np.sort() 후 반환된  :  None
np.sort() 후 original  :  [1 3 5 9]


## 2d 정렬

In [62]:
array2d = np.array([[8,12],
                   [7,1]])

print('rowwise sorting \n',np.sort(array2d, axis = 0))
print('columnwise sorting \n',np.sort(array2d, axis = 1))

rowwise sorting 
 [[ 7  1]
 [ 8 12]]
columnwise sorting 
 [[ 8 12]
 [ 1  7]]


## np.argsort()
- 정렬된 값의 인덱스 리턴

In [65]:
array1 = np.array([3,1,9,5])
print('ascending index : ',np.argsort(array1))
print('descending index : ',np.argsort(array1)[::-1])

ascending index :  [1 0 3 2]
descending index :  [2 3 0 1]


# 선형대수 연산

## 행렬 내적 np.dot()

In [68]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

print('A \n ', A)
print('B \n', B)

A 
  [[1 2 3]
 [4 5 6]]
B 
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [69]:
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

## 전치 행렬 np.transpose()

In [70]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])